spring.application.name=usuarios-api

# Conexión a la base de datos (obligatorio: viene del entorno)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT (obligatorio: viene del entorno)
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=86400000

# UPLOADS
app.s3.bucket=${S3_BUCKET:}
server.forward-headers-strategy=framework
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB